/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-05-31 09:38:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addRecordView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<title>ADD RECORD</title>\n");
      out.write("<style>\n");
      out.write("div.transbox {\n");
      out.write("  margin: 185px;\n");
      out.write("  background-color: #ffffff;\n");
      out.write("  border: 1px solid black;\n");
      out.write("  opacity: 1.0;\n");
      out.write("  filter: alpha(opacity=80); /* For IE8 and earlier */\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.transbox h1 {\n");
      out.write("  margin: 4%;\n");
      out.write("  font-weight: bold;\n");
      out.write("  color:#00008b;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div style='position:absolute;z-index:0;left:0;top:0;width:100%;height:100%'>\n");
      out.write("  <img src='http://i.huffpost.com/gen/1811926/images/o-BOOKS-facebook.jpg' style='width:1200px;height:1000px' alt='[]' />\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t");
 String user = request.getParameter("user");
      out.write("\n");
      out.write("    <div class=\"row\"></div>\n");
      out.write("    <div class=\"transbox\">\n");
      out.write("\t<div class=\"col-sm-6 col-md-4 col-md-offset-4\">\n");
      out.write("\t<h1 class=\"text-center login-title\">BOOKS DETAILS</h1>\n");
      out.write("\t<hr size = 4 ></hr>\n");
      out.write("\t<div class=\"account-wall\">\n");
      out.write("    <form action=\"addcontact\" method=\"post\">\n");
      out.write("    Book Name: <input type=\"text\" class = \"form-control\" placeholder = \"enter book name\" required></input><br>\n");
      out.write("    Edition: <input type=\"text\" class = \"form-control\" placeholder = \"enter book edition\" required></input><br>\n");
      out.write("    Author: <input type=\"text\" class = \"form-control\" placeholder =\"enter author name\" required></input><br>\n");
      out.write("    Publisher: <input type=\"text\" class = \"form-control\" placeholder = \"enter publisher\" required></input><br>\n");
      out.write("    Price: <input type=\"text\" class = \"form-control\" placeholder =\"enter price of the book\"required></input><br>\n");
      out.write("    Seller: <input type=\"text\" class = \"form-control\" placeholder = \"enter seller name\" required></input><br>\n");
      out.write("    <input type=\"hidden\" name=\"user\" value=\"rachana\"></input>\n");
      out.write("    <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">ADD RECORD</button> \n");
      out.write("    </form>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
