/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-05 13:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;
import com.bvrit.StayBookish.dao.BookDAO;
import com.bvrit.StayBookish.dao.BookPojo;

public final class bookView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write(" <link href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\">   \n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" \n");
      out.write("href=\"http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css\"></style>\n");
      out.write("<script type=\"text/javascript\" \n");
      out.write("src=\"http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" \n");
      out.write("src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function(){\n");
      out.write("    $('#myTable').dataTable();\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("  <style>\n");
      out.write("  ");
 String user = (String)session.getAttribute("user");
      out.write("\n");
      out.write("    /* Remove the navbar's default margin-bottom and rounded borders */ \n");
      out.write("    .navbar {\n");
      out.write("      margin-bottom: 0;\n");
      out.write("      border-radius: 0;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    /* Add a gray background color and some padding to the footer */\n");
      out.write("    footer {\n");
      out.write("      background-color: #f2f2f2;\n");
      out.write("      padding: 25px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("  .carousel-inner img {\n");
      out.write("      width: 100%; /* Set width to 100% */\n");
      out.write("      margin: auto;\n");
      out.write("      min-height:200px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* Hide the carousel text when the screen is less than 600 pixels wide */\n");
      out.write("  @media (max-width: 600px) {\n");
      out.write("    .carousel-caption {\n");
      out.write("      display: none; \n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("  #searchbox\n");
      out.write("{\n");
      out.write("    background-color: #eaf8fc;\n");
      out.write("    background-image: linear-gradient(#fff, #d4e8ec);\n");
      out.write("    border-radius: 35px;    \n");
      out.write("    border-width: 5px;\n");
      out.write("    border-style: solid;\n");
      out.write("    border-color: #c4d9df #a4c3ca #83afb7;            \n");
      out.write("    width: 700px;\n");
      out.write("    height: 70px;\n");
      out.write("    padding: 10px;\n");
      out.write("    margin: 100px auto 50px;\n");
      out.write("    overflow: hidden; /* Clear floats */\n");
      out.write("}\n");
      out.write("#search{\n");
      out.write("    width:550px;\n");
      out.write("    height:40px;\n");
      out.write("    \n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"jumbotron\">\n");
      out.write("  <div>\n");
      out.write("  <center><img src = \"logo.png\"></center>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("    <h1>STAY BOOKISH</h1>      \n");
      out.write("    <p>You Request We Sell</p>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-inverse\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>                        \n");
      out.write("      </button>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("      <ul class=\"nav navbar-nav\">\n");
      out.write("        <li ><a href=\"welcomeView.jsp\">Home</a></li>\n");
      out.write("        \n");
      out.write("        <li class=\"active\"><a href=\"bookView.jsp\">Books</a></li>\n");
      out.write("        <li><a href=\"sell\">Sell</a></li>\n");
      out.write("       \n");
      out.write("      </ul>\n");
      out.write("     ");
 if(user != null){ 
      out.write("\n");
      out.write("         <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("            <li class=\"active\"><a href=\"\">Welcome ");
      out.print(user );
      out.write("</a></li>\n");
      out.write("            <li><a href=\"cartView.jsp\"><span class=\"glyphicon glyphicon-shopping-cart\"></span> Cart</a></li>\n");
      out.write("             <li ><a href=\"loginView.jsp\">Logout</a></li>\n");
      out.write("         </ul>\n");
      out.write("      ");
 }else{ 
      out.write("\n");
      out.write("        <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("        <li><a href=\"loginView.jsp\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n");
      out.write("      </ul>\n");
      out.write("      ");
} 
      out.write(" \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("<h2 align=\"center\">Books</h2>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class=\"table-responsive\">\n");
      out.write("<table id=\"myTable\" class=\"table table-striped\" width=\"100%\" >\n");
      out.write("\n");
      out.write("  <thead valign=\"bottom\">\n");
      out.write("       <th align=\"center\">Book</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Name</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Author</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Edition</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Publisher</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Course</th>\n");
      out.write("       <th data-sortable=\"true\">Price</th>\n");
      out.write("       <th data-sortable=\"true\">Status</th>\n");
      out.write("       <th data-sortable=\"true\">Quantity</th>\n");
      out.write("       <th>Buy</th>\n");
      out.write("   </thead>\n");
      out.write("   <tbody>\n");
 
BookDAO rdao = new BookDAO();
ArrayList<BookPojo> list = rdao.getAllBooks();
for(BookPojo book : list) {
      out.write("\n");
      out.write("  <tr valign=\"top\">\n");
      out.write("       <td><img width='150' height='200' src=displayphoto?bid=");
      out.print(book.getBid());
      out.write("></td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getBname());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getAuthor());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getEdition());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getPublisher());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getYear());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getPrice());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getStatus());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getQuantity());
      out.write("</td>\n");
      out.write("       <td align=\"center\"><a href=\"buy?bid=");
      out.print(book.getBid());
      out.write("\">Buy</a></td>\n");
      out.write("    \n");
      out.write("  </tr>\n");
 }
      out.write("\n");
      out.write(" </tbody>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
