/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-11 14:15:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;
import com.bvrit.StayBookish.dao.BookDAO;
import com.bvrit.StayBookish.dao.BookPojo;
import java.io.*;
import java.util.*;
import java.sql.*;
import com.bvrit.StayBookish.dao.CartDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 String user = (String)session.getAttribute("user"); 
      out.write("\n");
      out.write(" \n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title></title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"css/agency.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom Fonts -->\n");
      out.write("    <link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("   \n");
      out.write("    <script>\n");
      out.write("$(document).ready(function(){\n");
      out.write("    $('#myTable').dataTable();\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</head>\n");


String message = request.getParameter("msg");
if(message != null){
out.print(message);
}

      out.write("\n");
      out.write("\n");
      out.write("<body id=\"page-top\" class=\"index\" >\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav class=\"navbar navbar-default navbar-fixed-top\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header page-scroll\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand page-scroll\" href=\"#page-top\">Home</a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                    <li class=\"hidden\">\n");
      out.write("                        <a href=\"#page-top\"></a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#bookView\">Books</a>\n");
      out.write("                       \n");
      out.write("                    </li>\n");
      out.write("                    \n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#sell\">Sell</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#about\">About</a>\n");
      out.write("                    </li>\n");
      out.write("                    \n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#contact\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                    <a href=\"#cartView\"><span class=\"page-scroll \"></span> Cart</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container-fluid -->\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Header -->\n");
      out.write("    <header>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"intro-text\">\n");
      out.write("                <div class=\"intro-heading\">Welcome To StayBookish!</div>\n");
      out.write("               \n");
      out.write("                 <div class=\"intro-lead-in\">You Request We Sell</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("   <!-- About Section -->\n");
      out.write("    <section id=\"bookView\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    <h2 class=\"section-heading\">Books</h2>\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Stay Bookish.</h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <ul class=\"timeline\">\n");
      out.write("                        <li>\n");
      out.write("                         <div class=\"table-responsive\">\n");
      out.write("<table id=\"myTable\" class=\"table table-striped\" width=\"100%\" >\n");
      out.write("\n");
      out.write("  <thead valign=\"bottom\">\n");
      out.write("       <th align=\"center\">Book</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Name</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Author</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Edition</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Publisher</th>\n");
      out.write("       <th align=\"center\" data-sortable=\"true\">Course</th>\n");
      out.write("       <th data-sortable=\"true\">Price</th>\n");
      out.write("       <th data-sortable=\"true\">Status</th>\n");
      out.write("       <th data-sortable=\"true\">Quantity</th>\n");
      out.write("       <th>Buy</th>\n");
      out.write("   </thead>\n");
      out.write("   <tbody>\n");
 
BookDAO rdao = new BookDAO();
ArrayList<BookPojo> list = rdao.getAllBooks();
for(BookPojo book : list) {
      out.write("\n");
      out.write("  <tr valign=\"top\">\n");
      out.write("       <td><img width='150' height='200' src=displayphoto?bid=");
      out.print(book.getBid());
      out.write("></td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getBname());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getAuthor());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getEdition());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getPublisher());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getYear());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getPrice());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getStatus());
      out.write("</td>\n");
      out.write("       <td align=\"center\">");
      out.print(book.getQuantity());
      out.write("</td>\n");
      out.write("       <td align=\"center\"><a href=\"buy?bid=");
      out.print(book.getBid());
      out.write("\">Buy</a></td>\n");
      out.write("    \n");
      out.write("  </tr>\n");
 }
      out.write("\n");
      out.write(" </tbody>\n");
      out.write("</table>\n");
      out.write("</div>   \n");
      out.write("                                \n");
      out.write("                        </li>\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                      \n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- About Section -->\n");
      out.write("    <section id=\"sell\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    \n");
      out.write("                     <div id=\"p\" class=\"container\">\n");
      out.write("        <h1 id=\"index\"> SIGN UP </h1><br><br>\n");
      out.write("        <div class=\"row\">\n");
      out.write("        <form  action=\"signup\" method=\"post\" class=\"col-md-4 col-md-offset-4\">\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        <label for=\"Name\">Username:</label>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"user\" placeholder=\"Enter name\">\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        <label for=\"Password\">Password:</label>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("        <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Enter password\">\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        <label for=\"Phone\">Phone:</label>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("        <input type=\"tel\" class=\"form-control\" name=\"phone\" placeholder=\"Enter phone no.\" required>\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <br><br><div class=\"form-group\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        <label for=\"Email\">Email:</label>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("        <input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Enter email\">\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <br><br>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        <label for=\"address\">Address:</label>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("         <input type=\"text\" class=\"form-control\" name=\"address\" placeholder=\"Enter address\">\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        <center>\n");
      out.write("        <input type=\"submit\" class=\"btn btn-primary\" value=\"Sign up\"></a>\n");
      out.write("        <a href=\"#loginView\">Already have an account?Then login</a>\n");
      out.write("        </center>\n");
      out.write("        </form>\n");
      out.write("        </div>\n");
      out.write("        </div> \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("<!-- About Section -->\n");
      out.write("    <section id=\"loginView\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    \n");
      out.write("                     <div id=\"p\" class=\"container\">\n");
      out.write("        <h1 id=\"index\"> LOGIN </h1><br><br>\n");
      out.write("        <div class=\"row\">\n");
      out.write("        <form  action=\"login\" method=\"post\" class=\"col-md-4 col-md-offset-4\">\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        <label for=\"Name\">Username:</label>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"user\" placeholder=\"Enter name\">\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        <label for=\"Name\">Password:</label>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-8\">\n");
      out.write("        <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Enter password\">\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        <center>\n");
      out.write("        <input type=\"submit\" class=\"btn btn-primary\" value=\"Login\"></a>\n");
      out.write("        <a href=\"signupView.jsp\" class=\"btn btn-primary\">Signup</a><br>\n");
      out.write("        <a href=\"ForgotPasswordView.jsp\" class=\"btn btn-link\">Forgot Password</a>\n");
      out.write("        </center>\n");
      out.write("        </form>\n");
      out.write("        </div>\n");
      out.write("        </div>                    </div> \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("    <!-- About Section -->\n");
      out.write("    <section id=\"about\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    <h2 class=\"section-heading\">About</h2>\n");
      out.write("                    <h3 class=\"section-subheading text-muted\">Stay Bookish.</h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <ul class=\"timeline\">\n");
      out.write("                        <li>\n");
      out.write("                            <div class=\"timeline-image\">\n");
      out.write("                                <img class=\"img-circle img-responsive\" src=\"img/about/1.jpeg\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"timeline-panel\">\n");
      out.write("                                <div class=\"timeline-heading\">\n");
      out.write("                                   \n");
      out.write("                                    <h4 class=\"subheading\">Beginnings</h4>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"timeline-body\">\n");
      out.write("                                    <p class=\"text-muted\">It has been more than a decade for the use of inter\n");
      out.write("net to be much common in each\n");
      out.write("individual house. The revolution of internet has in\n");
      out.write("fluenced all types of age groups from seniors\n");
      out.write("to teenagers; from veterans to trainees, each and e\n");
      out.write("very person had his way of learning the\n");
      out.write("method and using it for his own convenience. From l\n");
      out.write("eisure to fantasy, from shopping to studying\n");
      out.write("from education to gaming, internet had its dominanc\n");
      out.write("e compared to any other form of medium.\n");
      out.write("Internet became the easiest and the cheapest way to\n");
      out.write("reach the global network. Multiple facets\n");
      out.write("were added including attractive advertising, live v\n");
      out.write("ideos, simplified usages etc. Internet became a\n");
      out.write("good source for marketing and selling products. Int\n");
      out.write("ernet became the new catalog for product\n");
      out.write("sales for retail companies. The medium of newspaper\n");
      out.write("lost its importance for advertising products\n");
      out.write("to internet</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"timeline-inverted\">\n");
      out.write("                            <div class=\"timeline-image\">\n");
      out.write("                                <img class=\"img-circle img-responsive\" src=\"img/about/2.jpeg\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"timeline-panel\">\n");
      out.write("                                <div class=\"timeline-heading\">\n");
      out.write("                                    \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"timeline-body\">\n");
      out.write("                                    <p class=\"text-muted\">By using our staybookish website you will be able to sell and books online very easily.s</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                       \n");
      out.write("                        \n");
      out.write("                      \n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- Clients Aside -->\n");
      out.write("    <aside class=\"clients\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <img src=\"img/logos/envato.jpg\" class=\"img-responsive img-centered\" alt=\"\">\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <img src=\"img/logos/designmodo.jpg\" class=\"img-responsive img-centered\" alt=\"\">\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <img src=\"img/logos/themeforest.jpg\" class=\"img-responsive img-centered\" alt=\"\">\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <img src=\"img/logos/creative-market.jpg\" class=\"img-responsive img-centered\" alt=\"\">\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </aside>\n");
      out.write("    \n");
      out.write("    <!-- Contact Section -->\n");
      out.write("    <section id=\"contact\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    <h2 class=\"section-heading\">Contact Us</h2>\n");
      out.write("                    <h3 class=\"section-subheading text-muted\"></h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <form name=\"sentMessage\" id=\"contactForm\" novalidate>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" placeholder=\"Your Name *\" id=\"name\" required data-validation-required-message=\"Please enter your name.\">\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <input type=\"email\" class=\"form-control\" placeholder=\"Your Email *\" id=\"email\" required data-validation-required-message=\"Please enter your email address.\">\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <input type=\"tel\" class=\"form-control\" placeholder=\"Your Phone *\" id=\"phone\" required data-validation-required-message=\"Please enter your phone number.\">\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <textarea class=\"form-control\" placeholder=\"Your Message *\" id=\"message\" required data-validation-required-message=\"Please enter a message.\"></textarea>\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"clearfix\"></div>\n");
      out.write("                            <div class=\"col-lg-12 text-center\">\n");
      out.write("                                <div id=\"success\"></div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-xl\">Send Message</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("     <!-- About Section -->\n");
      out.write("    <section id=\"cartView\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    \n");
      out.write("                     <div id=\"p\" class=\"container\">\n");
      out.write("                     <div class=\"container\">\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-inverse\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>                        \n");
      out.write("      </button>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("   \n");
      out.write("      \n");
      out.write("       \n");
      out.write("       \n");
      out.write("      </div></nav>\n");
      out.write("\n");
      out.write("\t<table id=\"cart\" class=\"table table-hover table-condensed\">\n");
      out.write("    \t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width:80%\">Product</th>\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width:30%\">Price</th>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width:30%\"></th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t");
 CartDAO crdao = new CartDAO();
					
					int sum = 0;
                    
                    for(BookPojo book : list) {
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td data-th=\"Product\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-2 hidden-xs\"><img width='150' height='200' src=displayphoto?bid=");
      out.print(book.getBid());
      out.write("  alt=\"...\" class=\"img-responsive\"/></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"nomargin\">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp ");
      out.print( book.getBname() );
      out.write("</h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp Author:");
      out.print(book.getAuthor() );
      out.write("  &nbsp &nbsp Edition:");
      out.print(book.getEdition());
      out.write("<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp Publisher:");
      out.print(book.getPublisher() );
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<td data-th=\"Price\">Rs.");
      out.print(book.getPrice() );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t");
sum = sum + Integer.parseInt(book.getPrice()); 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<td class=\"actions\" data-th=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"deletebook?bid=");
      out.print(book.getBid());
      out.write("\"><button class=\"btn btn-danger btn-sm\"><i class=\"fa fa-trash-o\"></i></button></a>\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t<tfoot>\n");
      out.write("\t\t\t\t\t\t<tr class=\"visible-xs\">\n");
      out.write("\t\t\t\t\t\t\t<td class=\"text-center\"><strong>Total Rs.");
      out.print(sum);
      out.write("</strong></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"bookView.jsp\" class=\"btn btn-warning\"><i class=\"fa fa-angle-left\"></i> Continue Shopping</a></td>\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" class=\"hidden-xs\"></td>\n");
      out.write("\t\t\t\t\t\t\t<td class=\"hidden-xs text-center\"><strong>Total Rs.");
      out.print(sum );
      out.write("</strong></td>\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"paymentView.jsp\" class=\"btn btn-success btn-block\">Checkout <i class=\"fa fa-angle-right\"></i></a></td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</tfoot>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("</div>\n");
      out.write("                </div> \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("  \n");
      out.write("   \n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"js/jquery.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Plugin JavaScript -->\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\n");
      out.write("    <script src=\"js/classie.js\"></script>\n");
      out.write("    <script src=\"js/cbpAnimatedHeader.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Contact Form JavaScript -->\n");
      out.write("    <script src=\"js/jqBootstrapValidation.js\"></script>\n");
      out.write("    <script src=\"js/contact_me.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom Theme JavaScript -->\n");
      out.write("    <script src=\"js/agency.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
